### ISSUE TITLE
Multiple mount parameters appear to map to the same location

### ISSUE THREAD

**Issue by Chris-Schnaufer** [Computational-Plant-Science/plantit#336]
I am running my workflow using the (scif)[https://sci-f.github.io/] file system. The workflow is run with a shell script that calls various `scif` apps in order. There are checkpoint files that `scif` creates in each app-specific folder (example below). After the first app is run, the checkpoint file is found in the app-specific folder of the second, and subsequent app.

My workflow results can be found and downloaded from [CyVerse](https://data.cyverse.org/dav-anon/iplant/home/schnaufer/PlantIT_results/7362b651-9a4c-42aa-8c17-91545af6bd0f.zip)

The issue appears to be the following section of my [yaml](https://github.com/AgPipeline/drone-makeflow/blob/main/plantit.yaml) file where I am specifying mounts to ensure the necessary folders are write-enabled. The `workflow.jx.makeflowlog` file is written by the `soilmask` app, and then found by the `plotclip` app. See the the relevant output messages following the yaml snippet.

*YAML*
```yaml
mount:
  - /scif/apps/src
  - /scif/data/soilmask
  - /scif/data/plotclip
  - /scif/data/find_files2json
  - /scif/data/merge_csv
```

*Messages*
```
...
[soilmask] executing /bin/bash /scif/apps/soilmask/scif/runscript
parsing /scif/apps/src/soilmask_workflow.jx...
local resources: 64 cores, 128595 MB memory, 15 MB disk
max running local jobs: 64
checking /scif/apps/src/soilmask_workflow.jx for consistency...
/scif/apps/src/soilmask_workflow.jx has 1 rules.
creating new log file /scif/data/soilmask/workflow.jx.makeflowlog...
...
[plotclip] executing /bin/bash /scif/apps/plotclip/scif/runscript
parsing /scif/apps/src/plotclip_workflow.jx...
local resources: 64 cores, 128595 MB memory, 15 MB disk
max running local jobs: 64
checking /scif/apps/src/plotclip_workflow.jx for consistency...
/scif/apps/src/plotclip_workflow.jx has 1 rules.
recovering from log file /scif/data/plotclip/workflow.jx.makeflowlog...
...
```
As can be seen above, the log file is recovered even though it shouldn't exist (since the app hasn't run yet)

**Comment by Chris-Schnaufer** [comment]
@w-bonelli The cause appears to be here in [tasks.py](https://github.com/Computational-Plant-Science/plantit/blob/a59e65f00612bf18b0404d900bca3cd3e7b648f3/plantit/plantit/utils/tasks.py#L21) where `workdir` is used for any mount not using the format of `<host-path>:<mount-path>`.

**Comment by Chris-Schnaufer** [comment]
I opened this PR to address the issue: https://github.com/Computational-Plant-Science/plantit/pull/338

**Comment by w-bonelli** [comment]
#338 is deployed now if you'd like to test, this should be resolved but will wait for confirmation before closing. Thanks again for the PR.

**Comment by Chris-Schnaufer** [comment]
@w-bonelli This looks to working well (job d10e7ff3-8fb9-40f8-a91f-edbc1da96ca5)

**Comment by w-bonelli** [comment]
thanks @Chris-Schnaufer, I logged into the cluster and checked it out, it looks like it did create the correct folder structure. I am not very familiar with the workflow but it seems to have run successfully, although the `result.json` file is excluded from outputs in the `plantit.yaml` config so only logs were uploaded to CyVerse
