### ISSUE TITLE
Input selection on flow submision page

### ISSUE THREAD

**Issue by koalaspirit** [Computational-Plant-Science/plantit#34]
Folders that are deeper than the second hierarchy level of the folder structure can not be selected for job submissions.

<img width="1101" alt="Screen Shot 2020-10-27 at 2 04 10 PM" src="https://user-images.githubusercontent.com/942987/97342957-4dba1d00-185d-11eb-912e-19d024d63bf7.png">

**Comment by w-bonelli** [comment]
Fixed by e6a05c6
