### ISSUE TITLE
Patch Error from 12/9/2022: Wrong folder zipped in results

### ISSUE THREAD

**Issue by koalaspirit** [Computational-Plant-Science/plantit#345]
I attach two outputs of jobs that show as completed successfully but zipped files in a wrong folder. The jobs were ran on the clusters Sapelo2 and Puma respectively. 

[_iplant_home_abucksch_DIRT2DTestDec9_aa1ebe84-e4ee-465e-9579-8da92125c7c6.zip](https://github.com/Computational-Plant-Science/plantit/files/10200164/_iplant_home_abucksch_DIRT2DTestDec9_aa1ebe84-e4ee-465e-9579-8da92125c7c6.zip)
[_iplant_home_abucksch_DIRT2DTestDec9Puma_879deaa5-0717-422f-87a6-97af9744d790.zip](https://github.com/Computational-Plant-Science/plantit/files/10200165/_iplant_home_abucksch_DIRT2DTestDec9Puma_879deaa5-0717-422f-87a6-97af9744d790.zip)

**Comment by koalaspirit** [comment]
Just checked cmd output of task 879deaa5-0717-422f-87a6-97af9744d790:

```
cp: cannot stat '/output.csv': No such file or directory
cat: /home/u29/bucksch/plantit/879deaa5-0717-422f-87a6-97af9744d790//output..csv: No such file or directory
```

The problems seems to be a typo in the filenames and folder paths.

**Comment by w-bonelli** [comment]
@koalaspirit are you still seeing this issue?
