### ISSUE TITLE
Wall time and memory limit 

### ISSUE THREAD

**Issue by koalaspirit** [Computational-Plant-Science/plantit#35]
Submission is limited to 10GB memory and 10min wall time. Copy-paste error from the sandbox?

<img width="1022" alt="Screen Shot 2020-10-27 at 2 04 54 PM" src="https://user-images.githubusercontent.com/942987/97343047-662a3780-185d-11eb-8098-9374868fa71b.png">

**Comment by w-bonelli** [comment]
Cluster resources now specified in flow `plantit.yaml` and shown on submission page
