### ISSUE TITLE
No connection to GitHub

### ISSUE THREAD

**Issue by ashuraj123** [Computational-Plant-Science/plantit#359]
Logging into GitHub through PlantIT always shows the screen attached. Any help with that?

<img width="1792" alt="Screenshot 2023-02-15 at 12 15 45 PM" src="https://user-images.githubusercontent.com/125496574/219117445-cad84079-4f65-499d-9a46-c6efc81908bb.png">

**Comment by w-bonelli** [comment]
It was a GitHub OAuth app integration config issue. Sorry about that! Working for you now?
