### ISSUE TITLE
Only users with github account are shown in the user list

### ISSUE THREAD

**Issue by koalaspirit** [Computational-Plant-Science/plantit#37]
User that do not contribute flows don't necessarily have a github account. These users are not shown on the user page. Distinguishing contributors from users would be a good.

Update: Also new users with linked github account are not shown.

**Comment by w-bonelli** [comment]
@koalaspirit I see the same users on the users page and in the shell... namely the 6 in the lab, do you know which users have logged in but are missing?

```
>>> users = User.objects.all()
>>> len(users)
6
```

**Comment by koalaspirit** [comment]
It seems like the users appeared after they linked their github accounts. Using only the cyverse login does not make them appear on the webpage.

**Comment by w-bonelli** [comment]
All users now shown on users page, even when user hasn't logged into GitHub.

GH login in is still necessary to load flows, although we could cache them if we don't want to require every user to have a GitHub account.
