### ISSUE TITLE
Clicking runs in the file tree does not respond

### ISSUE THREAD

**Issue by koalaspirit** [Computational-Plant-Science/plantit#43]
<img width="755" alt="Screen Shot 2020-11-15 at 6 52 32 AM" src="https://user-images.githubusercontent.com/942987/99184193-3610de80-270f-11eb-82f3-7d59b9b37b08.png">

The file tree on the top only responds to clicks in the first two levels.

**Comment by w-bonelli** [comment]
Currently there's no separate runs page. Maybe we should have one? Clicking on the run ID just routes back to the same page, so it looks like there's no response.

**Comment by koalaspirit** [comment]
Yes, there is a separate runs page. Its the tab in the profile

**Comment by w-bonelli** [comment]
Oh, I was thinking of that as a component, yes, you're right... What about removing the "runs" crumb altogether, and prepending "Run: 266d2..." on the last level?

**Comment by koalaspirit** [comment]
Goog solution.


—————————————————————————————————————————————————————————
Dr. Alexander Bucksch - Assistant Professor

Department of Plant Biology / Institute of Bioinformatics /
Warnell School of Forestry and Natural Resources

Associate Editor at Plant Methods - https://plantmethods.biomedcentral.com/
Associate Editor at Frontiers in Plant Science - https://www.frontiersin.org/journals/plant-science

Miller Plant Sciences
120 Carlton Street
Athens, GA 30602, USA

p: +1-706-542-1823
e: bucksch@uga.edu<mailto:bucksch@uga.edu>
w: http://www.computational-plant-science.org
Twitter: @koalaspirit

Integrated Plant Sciences: http://ips.uga.edu



[cid:7DD74C30-131A-4564-AC01-5FD2A990BCDF]

On Nov 18, 2020, at 6:58 PM, w-bonelli <notifications@github.com<mailto:notifications@github.com>> wrote:


Oh, I was thinking of that as a component, yes, you're right... What about removing the "runs" crumb altogether, and prepending "Run: 266d2..." on the last level?

**Comment by w-bonelli** [comment]
Resolved by 7568cfb
