### ISSUE TITLE
User defined names for runs

### ISSUE THREAD

**Issue by koalaspirit** [Computational-Plant-Science/plantit#44]
It is hard to identify a particular run as a user. Would it be possible to give user-defined names when creating the run?

**Comment by w-bonelli** [comment]
Currently runs are shown on a per-user basis (there's no central place to view all of them, only runs belonging to a user are shown on that user's page).

Do we want to create a page showing all users' runs? If so, we could just label each run with user info on that page.

I'm planning to add the ability to tag runs with arbitrary text too, as part of the MIAPPE integration. Would that cover this case? Currently run names are GUIDs; with user-defined names we'd need to manually enforce uniqueness.

**Comment by w-bonelli** [comment]
Supported after 02470bc
