### ISSUE TITLE
Scheduler timeouts on non-sandbox deployment targets not detected

### ISSUE THREAD

**Issue by w-bonelli** [Computational-Plant-Science/plantit#48]
When walltime is exceeded on cluster deployment targets, run status is not updated and runs never enter the `Completed` or `Failed` state.

Some possible options:
- server-side polling (server periodically checks cluster scheduler; aborts run if associated job completes before completion status update is received)
- cluster-side health checks (CLI emits periodic status updates; server aborts run if completion status update not received within acceptable delay)

**Comment by koalaspirit** [comment]
Solution 1 is better in my opinion. Just a quick poll after the known wall time is reached. That way we can automatically restart with an increased wall-time and take some job monitoring burden from the user. 

Maybe we simply restart with the known maximum wall time for the restart. If failed again we simply double.

**Comment by w-bonelli** [comment]
After a2e235b, runs should automatically enter the `Failed` state if they don't complete after twice the requested walltime. Maybe we can make this multiplier configurable going forward.

Currently working on polling the cluster/restart after a timeout.

**Comment by w-bonelli** [comment]
Should be resolved by 1c8124f
