### ISSUE TITLE
Failed jobs do not clean up correctly on the cluster side

### ISSUE THREAD

**Issue by koalaspirit** [Computational-Plant-Science/plantit#54]
Failed jobs leave their data on the cluster side causing a disk quota reached error.

Data could be stored on scratch with no quota rather than home.

**Comment by w-bonelli** [comment]
Should we use the /scratch directory on Stampede2 for everything? E.g., as working directory as well as data storage?

**Comment by w-bonelli** [comment]
Long-term, we could think about adding an optional feature to PlantIT to periodically clear data on deployment targets (periodic Celery task should work). Depends on #46.

**Comment by w-bonelli** [comment]
Working as of 48dd3c9
