### ISSUE TITLE
User authenticated cluster deployment

### ISSUE THREAD

**Issue by koalaspirit** [Computational-Plant-Science/plantit#91]
Currently, users can use every available cluster. However, users should be able to access restricted private resources too.

An authentication that does not require storing usernames and passwords would be the best way to go. 

A way to get a private resource registered is also needed.

**Comment by w-bonelli** [comment]
We could maybe allow users to enter username/password each time for one-off submissions, and not store the data? Then for persistent access we could generate a keypair, and either require the user to move the public key to the deployment target or copy it automatically if they enter their auth info.

This and #46 have some overlap as well.

**Comment by koalaspirit** [comment]
Right. That’s what we talked before

Sent from my iPhone

On Feb 1, 2021, at 11:43 PM, w-bonelli <notifications@github.com> wrote:

﻿ [EXTERNAL SENDER - PROCEED CAUTIOUSLY]


We could maybe allow users to enter username/password each time for one-off submissions, and not store the data? Then for persistent access we could generate a keypair, and either require the user to move the public key to the deployment target or copy it automatically if they enter their auth info.

This and #46<https://github.com/Computational-Plant-Science/plantit/issues/46> have some overlap as well.

**Comment by w-bonelli** [comment]
Username/password authentication to public deployment targets is now supported.
